### ISSUE TITLE
Not working in immersive AR mode 

### ISSUE THREAD

**Issue by lue** [mwbeene/aframe-cursor-teleport#2]
Great component! Works very well on desktop and mobile. However, it seems to be not working in immersive AR mode on Android. After entering it (clicking AR button) clicks on the screen stop working (nothing happens). Tested on the live examples with Pixel 2 and Chrome Beta channel.

**Comment by mwbeene** [comment]
Thanks! The cursor-teleport component doesn't work with the immersive AR mode at the moment since it relies on the scene's DOM element to get the x and y positions of the user's touch. This goes away once you enter the immersive view. I do want to integrate this though since the positional tracking of AR would be nice to have.

Using the a-frame's new DOM overlay feature, I'm able to get cursor-teleport working in AR but as far as I can tell this requires adding some html and css to the scene which I was having a hard time doing programmatically through the component. Seems like the html and css for the DOM overlay needs to be set up before the scene is initialized.

I put together a working version over here:
[https://paragram.io/mb-sandbox/ar-teleport/](https://paragram.io/mb-sandbox/ar-teleport/)

Maybe the best way to handle this is to allow the user to create their own AR overlay in html/css, then specify its selector in the cursor-component schema. I'd probably want to create a separate example for this since the html/css setup would be a little convoluted for non-AR users. Let me know if you have any thoughts and I'll try incorporate this next week.

**Comment by lue** [comment]
Thank you for the working version! It is very intuitive mechanics for the immersive AR, I like it a lot. However, with this implementation the octahedrons became not responsive. I will tinker with it next week.
