### ISSUE TITLE
Textured GLTF are not working with the component attached and master aframe

### ISSUE THREAD

**Issue by lue** [mwbeene/aframe-cursor-teleport#3]
Probably not related to this component, but I noticed that if it used with the latest master aframe the textured gltf models are not displayed. Minimal example https://glitch.com/edit/#!/join/36d8681d-2de0-4dc7-8746-b5b948a668d1 

If you comment out master aframe and use 1.0.4 version everything works. 

If you use master version and comment out the teleport component everything works again.

It is only in combination with latest aframe and teleport component the textured gltf model is not displayed. (Simple gltf models with no textures still work).

**Comment by Kershawj** [comment]
Just to add to this and seeing exactly the same problem.
If you export or use a GLTF model using GLTF+bin+texture it works. GTLF+bin (so embedding textures) fails, as does GLB.
Error (or rather warning) that's shown when failing:

`components:gltf-model:warn Cannot read property 'createObjectURL' of undefined`

**Comment by mwbeene** [comment]
Hmm, I can't seem to replicate the issue.

@lue's glitch shows the loaded model (Mars) with textures when I view it. I also created a textured model using Blender and exported it both as glb and gltf (embedded) and both loaded with no issue using A-Frame 1.03 and 1.04

@Kershawj Any way you can replicate this on Glitch or send me an example?

**Comment by Kershawj** [comment]
@mwbeene Thanks for the reply and taking the time to look into it.

@lue's glitch does the trick to be honest but not sure the problem was made clear enough.
It does work on A-frame 1.0.3 and 1.0.4 but if you open the Glitch (https://glitch.com/edit/#!/join/36d8681d-2de0-4dc7-8746-b5b948a668d1) and change the A-frame version to 1.2.0 then you will see that model of Mars doesn't show up anymore.

So like I say the way to get around right now is to save out and use GLTF with separate textures, so as GLTF+BIN+Textures or use A-frame version 1.0.3 or 1.0.4 but embedded textures in say a GLB and A-frame 1.1.0 or 1.2.0 it will fail to show up as previously mentioned.

**Comment by krii1988** [comment]
Managed to figure this out, it's the variable 'self'.

Since version 1.1.0 in aframe.master.js's function "GLTFParser.prototype.loadTextureImage" there's a line:

	var URL = self.URL || self.webkitURL;

I figure both self's are conflicting; just renamed all of them to something else in 'aframe-cursor-teleport-component' and yay - running perfectly on aframe 1.2.0.

**Comment by oneWaveAdrian** [comment]
@krii1988 doesn't work for me, could you create a PR?

**Comment by mwbeene** [comment]
Thanks @krii1988 and @oneWaveAdrian. I'll also experiment with it this week.

**Comment by oneWaveAdrian** [comment]
@mwbeene @krii1988 any news on this PR?

**Comment by krii1988** [comment]
> @mwbeene @krii1988 any news on this PR?

Hey, sorry, just made it. Hopefully, it works for you!

**Comment by mwbeene** [comment]
@krii1988 @oneWaveAdrian

I checked out the PR and was having trouble viewing the diff since Angle/webpack is putting all of the code into a single line.

I did replicate @krii1988's change on my own branch, and everything works in A-Frame 1.2. I also simplified the "Custom" example and updated to A-Frame 1.2 so everything should be more clear. Just merged so we should be good to go for the textured gltf/glb issue.

Will still have look into the issue with Angle and webpack so that PRs are easier to review in the future.

Thank you all for your help!
